### ISSUE TITLE
Porting of TDDR to MNE

### ISSUE THREAD

**Issue by rob-luke** [frankfishburn/TDDR#1]
Dear Dr Fishburn,

I am in the field of auditory neuroscience and have enjoyed using your TDDR algorithm for motion correction with the NIRS Toolbox. I have found that your approach greatly improves the quality of my data.

I would like to port your algorithm to MNE. The MIT license for this project seems compatible with this idea. Are you ok with this? Would you like to be involved in this port (I am happy to do the boring bits like docstring, code formatting, data transformation, etc)? I will clearly cite your code and journal articles, but let me know if you want to be credited in a specific way.

You can see an example of the current analysis with MNE [here](https://mne.tools/dev/auto_tutorials/preprocessing/plot_70_fnirs_processing.html#sphx-glr-auto-tutorials-preprocessing-plot-70-fnirs-processing-py), and a rough timeline for what we have planned [here](https://github.com/mne-tools/mne-python/issues/7057).

Thanks,
Rob

**Comment by frankfishburn** [comment]
Hi Rob,

Glad you found the method useful!  Happy to see another toolkit adopt the method.  I probably won't have time to help but will probably take a look at MNE at some point. Providing a citation and links to the paper and this repo will be sufficient. I appreciate you asking.

Best,
Frank

**Comment by rob-luke** [comment]
Thanks Frank,

Appreciate your blessing. I will ping you when we have a pull request in case you do want to edit the way you are credited, but don't feel obliged to respond or make code edits.

Cheers,
Rob

**Comment by rob-luke** [comment]
Closing as we merged this in https://github.com/mne-tools/mne-python/pull/7556 and the docs can be found here https://mne.tools/dev/generated/mne.preprocessing.nirs.temporal_derivative_distribution_repair.html

Thanks for the great tool
