### ISSUE TITLE
Porting of TDDR in nirstorm

### ISSUE THREAD

**Issue by Edouard2laire** [frankfishburn/TDDR#3]
Dear Dr. Fishburn,

I recently read about your motion correction algorithm and would be interesting in porting it in our Nirs toolbox called Nirstorm (https://github.com/Nirstorm/nirstorm) which is a plugin of the software Brainstorm made for EEG/MEG analysis. 

I would like to add your algorithm in the list of the available motion correction algorithm available in our toolbox (with of course the proper citation to your article). Would that be ok for you? 

Best regards, 
Edouard

**Comment by frankfishburn** [comment]
Hi Edouard,

That's absolutely OK, I would just ask that you provide the reference to the paper and a link to this repo in your code and documentation. I'm also happy to link to your repo from here once its implemented.

Best,
Frank

**Comment by Edouard2laire** [comment]
Hi. Sorry, I forgot to update you. 

TDDR is now available also in NIRSTORM : 
![image](https://github.com/frankfishburn/TDDR/assets/24530402/be7d29cf-7272-4103-a096-a8acaa4f0e0f)
